### ISSUE TITLE
RedisConnectionException

### ISSUE THREAD

**Issue by korlu** [cleancodelabs/IdentityServer4.Contrib.Caching#1]
I have been trying to implement a Redis cache to allow me implement user password change from multiple client applications.  I think your package may help achieve my goal. However, I am having issue connecting to my Redis server, which is password protected. 

I am getting this error message:

RedisConnectionException: It was not possible to connect to the redis server(s). UnableToConnect on 192.168.xx.xx:5900/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 1s ago, last-write: 1s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 6s ago

I changed the default port for my Redis server.

Here is what I have in my Setup.cs file: 

services.AddIdentityServer()
// some code...
.AddDistributedRedisCache(options =>
            {
                var opts = new ConfigurationOptions
                {
                    AbortOnConnectFail = false,
                    // AllowAdmin = true,
                    Password = "my-password-here",
                    Ssl = false
                };
                opts.EndPoints.Add("192.168.xx.xx", 5900);
                options.ConfigurationOptions = opts;
                options.Configuration = "{192.168.xx.xx:5900}";
            }, options => options.CachingKeyPrefix = "_my-identityserver-caching-prefix_");

// more code....

Thank you.

**Comment by alsami** [comment]
Hi!

Did you try connecting to your redis cache with Stackexchange.Redis in a simple application before? I think the connection error has nothing to do with the package. It's part of Stackexchange.Redis, used as a peer dependency of Microsoft.Extensions.StackExchange.Redis

**Comment by alsami** [comment]
I think I found the issue and have fixed it. The build for version [1.0.1](https://travis-ci.com/cleancodelabs/IdentityServer4.Contrib.Caching/builds/113875836) is currently running. Please update the package as soon as it is available and let me know if it works!

Kind regards,
Sami

**Comment by korlu** [comment]
Okay, thank you Sami.

**Comment by korlu** [comment]
> I think I found the issue and have fixed it. The build for version [1.0.1](https://travis-ci.com/cleancodelabs/IdentityServer4.Contrib.Caching/builds/113875836) is currently running. Please update the package as soon as it is available and let me know if it works!
> 
> Kind regards,
> Sami

Sami, thank you so much.  It works now!

**Comment by alsami** [comment]
Happy to hear that! Enjoy
